# Colombia seimic global stats
(1st June, 1993 to 31st May, 2023)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

## Data Collection: 

The data was downloaded form Servicio geológico colombiano, http://bdrsnc.sgc.gov.co/paginas1/catalogo/index.php and splited in 14 files: "reporte???.xlsx"

## Data Wrangling

According with the Servicio geológico colombiano, the data was collected and made public in two campaigns:

* Firsh batch: from 1st of June, 1993 to 28th of Febraury, 2018. Registered by SEISAN software.
* Firsh batch: from 1st of March, 2018 to 31st of May, 2023. Registered by SeisComp33 software.  

See more details in the previous link.

In line with the above, the data is coming with different fields between them.

In [3]:
# List of file names
files_1st_batch = ['data/reporte9.xlsx', 'data/reporte1244.xlsx', 'data/reporte160.xlsx', 'data/reporte1805.xlsx', 'data/reporte1922.xlsx', 'data/reporte239.xlsx', 'data/reporte362.xlsx', 'data/reporte665.xlsx']
files_2nd_batch = ['data/reporte1091.xlsx', 'data/reporte1629.xlsx', 'data/reporte1796.xlsx', 'data/reporte871.xlsx', 'data/reporte974.xlsx', 'data/reporte97.xlsx']

# Empty list to store DataFrames
dfs_1st_batch = []
dfs_2nd_batch = []

# Read each file and append DataFrame to the list
for file_name in files_1st_batch:
    tmp_df = pd.read_excel(file_name)
    dfs_1st_batch.append(tmp_df)
    
for file_name in files_2nd_batch:
    tmp_df = pd.read_excel(file_name)
    dfs_2nd_batch.append(tmp_df)

# Concatenate the DataFrames
seismic_1st_batchFull = pd.concat(dfs_1st_batch)
seismic_1st_batchFull = seismic_1st_batchFull.reset_index(drop=True)
seismic_2nd_batchFull = pd.concat(dfs_2nd_batch)
seismic_2nd_batchFull = seismic_2nd_batchFull.reset_index(drop=True)

In [4]:
print("Describe for first batch")
seismic_1st_batchFull.describe()

Describe for first batch

,LATITUD (grados),LONGITUD (grados),PROFUNDIDAD (Km),MAGNITUD Ml,MAGNITUD Mw,# FASES,RMS (Seg),GAP (grados),ERROR LATITUD (Km),ERROR LONGITUD (Km),ERROR PROFUNDIDAD (Km)
count,173275.000000,173275.000000,173275.000000,173275.000000,4544.000000,173275.000000,173086.000000,173086.000000,173086.000000,173086.000000,173086.000000
mean,6.230927,-73.988323,99.446401,2.117948,3.438688,7.443463,0.449777,177.535231,6.625142,9.251236,11.397149
std,1.584885,1.513679,60.826182,0.704426,0.530064,4.643028,0.236118,61.328644,7.936443,9.856246,12.275819
min,-3.483000,-83.400000,0.000000,0.100000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.848000,-74.508000,24.100000,1.600000,3.100000,5.000000,0.300000,135.000000,3.300000,4.000000,5.900000
50%,6.784000,-73.174000,138.000000,2.000000,3.400000,6.000000,0.400000,174.000000,4.600000,6.200000,7.900000
75%,6.831000,-73.095000,146.900000,2.500000,3.700000,8.000000,0.500000,213.000000,6.900000,10.900000,11.600000
max,14.907000,-70.168000,700.000000,6.800000,7.100000,96.000000,9.400000,360.000000,99.900000,99.900000,99.900000

In [5]:
print("Columns name\n")
for i in seismic_1st_batchFull.columns.to_list():
    print(i)

Columns name

FECHA
HORA_UTC
LATITUD (grados)
LONGITUD (grados)
PROFUNDIDAD (Km)
MAGNITUD Ml
MAGNITUD Mw
DEPARTAMENTO
MUNICIPIO
# FASES
RMS (Seg)
GAP (grados)
ERROR LATITUD (Km)
ERROR LONGITUD (Km)
ERROR PROFUNDIDAD (Km)
ESTADO

In [6]:
print("Describe for second batch")
seismic_2nd_batchFull.describe()

Describe for second batch

,LATITUD (°),LONGITUD (°),PROF. (Km),MAGNITUD,FASES,RMS (Seg),GAP (°),ERROR LATITUD (Km),ERROR LONGITUD (Km),ERROR PROFUNDIDAD (Km)
count,126459.000000,126459.000000,126459.000000,126459.000000,126459.000000,126459.000000,126459.000000,126459.000000,126459.000000,126459.000000
mean,6.134687,-74.232196,85.593697,1.729508,17.493646,0.566562,135.683542,2.759717,2.907980,4.410459
std,1.911706,1.548449,58.579244,0.528979,12.842566,0.313320,53.897128,1.966607,2.181952,3.868208
min,-3.587000,-89.985000,-4.940000,0.100000,3.000000,0.000000,18.000000,0.000000,0.000000,0.000000
25%,5.176000,-75.221000,19.965000,1.400000,9.000000,0.300000,100.000000,1.273000,1.273000,2.100000
50%,6.761000,-73.507000,110.490000,1.700000,13.000000,0.500000,131.000000,2.121000,2.121000,3.500000
75%,6.831000,-73.163000,140.900000,2.000000,21.000000,0.800000,162.000000,3.722000,4.037000,6.400000
max,14.314000,-69.022000,461.870000,6.600000,123.000000,4.900000,353.000000,56.781000,56.781000,641.500000

In [7]:
print("Columns name\n")
for i in seismic_2nd_batchFull.columns.to_list():
    print(i)

Columns name

FECHA - HORA UTC
LATITUD (°)
LONGITUD (°)
PROF. (Km)
MAGNITUD
TIPO MAGNITUD
FASES
RMS (Seg)
GAP (°)
ERROR LATITUD (Km)
ERROR LONGITUD (Km)
ERROR PROFUNDIDAD (Km)
REGION
ESTADO

In [8]:
# Chosen columns of interest and renaming
seismic_1st_batch = seismic_1st_batchFull[['FECHA', 'HORA_UTC', 'LATITUD (grados)', 'LONGITUD (grados)', 'PROFUNDIDAD (Km)', 'MAGNITUD Ml', 'MAGNITUD Mw', 'DEPARTAMENTO', 'MUNICIPIO', 'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)', 'ESTADO']].copy()
seismic_1st_batch.rename(columns={"LATITUD (grados)": "LAT", "LONGITUD (grados)": "LONG", 'PROFUNDIDAD (Km)': "PROF.", "ERROR LATITUD (Km)": "ERR-LAT", "ERROR LONGITUD (Km)": "ERR-LONG", "ERROR PROFUNDIDAD (Km)": "ERR-PROF"}, inplace=True)

print("First batch", '\n')
for i in seismic_1st_batch.columns.to_list():
    print(i)

seismic_2nd_batch = seismic_2nd_batchFull[['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)', 'MAGNITUD', 'TIPO MAGNITUD', 'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)', 'REGION', 'ESTADO']].copy()
seismic_2nd_batch.rename(columns={"LATITUD (°)": "LAT", "LONGITUD (°)": "LONG", 'PROF. (Km)': "PROF.", "ERROR LATITUD (Km)": "ERR-LAT", "ERROR LONGITUD (Km)": "ERR-LONG", "ERROR PROFUNDIDAD (Km)": "ERR-PROF"}, inplace=True)

print("\nSecond batch", '\n')
for i in seismic_2nd_batch.columns.to_list():
    print(i)

First batch

FECHA
HORA_UTC
LAT
LONG
PROF.
MAGNITUD Ml
MAGNITUD Mw
DEPARTAMENTO
MUNICIPIO
ERR-LAT
ERR-LONG
ERR-PROF
ESTADO

Second batch

FECHA - HORA UTC
LAT
LONG
PROF.
MAGNITUD
TIPO MAGNITUD
ERR-LAT
ERR-LONG
ERR-PROF
REGION
ESTADO

## Standardizing

### Checking for duplicate rows

In [12]:
seismic_1st_batch[seismic_1st_batch.duplicated(subset=seismic_1st_batch.columns, keep=False)]

,FECHA,HORA_UTC,LAT,LONG,PROF.,MAGNITUD Ml,MAGNITUD Mw,DEPARTAMENTO,MUNICIPIO,ERR-LAT,ERR-LONG,ERR-PROF,ESTADO
55267,2005-02-28,23:34:42,6.813,-73.027,150.2,2.4,NaN,SANTANDER,CEPITA,5.6,10.9,7.9,Revisado
55268,2005-02-28,23:34:42,6.813,-73.027,150.2,2.4,NaN,SANTANDER,CEPITA,5.6,10.9,7.9,Revisado
74701,2009-06-11,01:50:05,4.697,-76.317,76.5,1.4,NaN,VALLE DEL CAUCA,EL_CAIRO,6.2,14.7,21.7,Revisado
74702,2009-06-11,01:50:05,4.697,-76.317,76.5,1.4,NaN,VALLE DEL CAUCA,EL_CAIRO,6.2,14.7,21.7,Revisado
74703,2009-06-11,02:20:57,6.815,-73.163,149.0,3.9,NaN,SANTANDER,LOS_SANTOS,3.6,6.8,9.3,Revisado
74704,2009-06-11,02:20:57,6.815,-73.163,149.0,3.9,NaN,SANTANDER,LOS_SANTOS,3.6,6.8,9.3,Revisado
74705,2009-06-11,03:45:52,6.810,-73.111,148.9,2.3,NaN,SANTANDER,LOS_SANTOS,4.3,10.9,11.7,Revisado
74706,2009-06-11,03:45:52,6.810,-73.111,148.9,2.3,NaN,SANTANDER,LOS_SANTOS,4.3,10.9,11.7,Revisado
74707,2009-06-11,04:21:21,6.772,-72.976,156.6,1.6,NaN,SANTANDER,CEPITA,7.9,9.3,9.2,Revisado
74708,2009-06-11,04:21:21,6.772,-72.976,156.6,1.6,NaN,SANTANDER,CEPITA,7.9,9.3,9.2,Revisado
74709,2009-06-11,06:25:51,7.477,-74.113,8.4,1.6,NaN,BOLIVAR,SAN_PABLO,4.9,8.2,6.2,Revisado
74710,2009-06-11,06:25:51,7.477,-74.113,8.4,1.6,NaN,BOLIVAR,SAN_PABLO,4.9,8.2,6.2,Revisado
74711,2009-06-11,06:27:40,7.734,-73.024,142.1,1.3,NaN,NORTE DE SANTANDER,CACHIRA,7.8,8.3,7.3,Revisado
74712,2009-06-11,06:27:40,7.734,-73.024,142.1,1.3,NaN,NORTE DE SANTANDER,CACHIRA,7.8,8.3,7.3,Revisado
74713,2009-06-11,06:31:28,3.847,-75.718,4.0,1.9,NaN,TOLIMA,RONCESVALLES,3.9,6.5,10.4,Revisado
74714,2009-06-11,06:31:28,3.847,-75.718,4.0,1.9,NaN,TOLIMA,RONCESVALLES,3.9,6.5,10.4,Revisado
74715,2009-06-11,06:43:17,6.847,-73.173,128.6,1.9,NaN,SANTANDER,ZAPATOCA,5.5,13.9,18.2,Revisado
74716,2009-06-11,06:43:17,6.847,-73.173,128.6,1.9,NaN,SANTANDER,ZAPATOCA,5.5,13.9,18.2,Revisado
74717,2009-06-11,06:44:23,6.796,-73.165,146.0,1.8,NaN,SANTANDER,LOS_SANTOS,3.7,8.6,9.8,Revisado
74718,2009-06-11,06:44:23,6.796,-73.165,146.0,1.8,NaN,SANTANDER,LOS_SANTOS,3.7,8.6,9.8,Revisado
74719,2009-06-11,06:56:18,6.893,-72.148,0.0,2.7,NaN,BOYACA,CUBARA,5.9,31.7,19.1,Revisado
74720,2009-06-11,06:56:18,6.893,-72.148,0.0,2.7,NaN,BOYACA,CUBARA,5.9,31.7,19.1,Revisado
74722,2009-06-11,07:32:14,7.228,-74.379,13.3,1.5,NaN,ANTIOQUIA,SEGOVIA,3.8,5.5,11.3,Revisado
74723,2009-06-11,07:32:14,7.228,-74.379,13.3,1.5,NaN,ANTIOQUIA,SEGOVIA,3.8,5.5,11.3,Revisado
74724,2009-06-11,08:27:18,6.780,-73.123,152.8,1.7,NaN,SANTANDER,LOS_SANTOS,4.0,7.5,8.8,Revisado
74725,2009-06-11,08:27:18,6.780,-73.123,152.8,1.7,NaN,SANTANDER,LOS_SANTOS,4.0,7.5,8.8,Revisado
74727,2009-06-11,10:33:10,8.271,-74.946,0.0,1.9,NaN,CORDOBA,AYAPEL,15.8,6.6,6.6,Revisado
74728,2009-06-11,10:33:10,8.271,-74.946,0.0,1.9,NaN,CORDOBA,AYAPEL,15.8,6.6,6.6,Revisado
74729,2009-06-11,10:44:01,6.869,-73.149,153.1,2.6,NaN,SANTANDER,LOS_SANTOS,6.3,9.5,17.3,Revisado
74730,2009-06-11,10:44:01,6.869,-73.149,153.1,2.6,NaN,SANTANDER,LOS_SANTOS,6.3,9.5,17.3,Revisado
74731,2009-06-11,10:44:02,6.814,-73.127,139.8,2.8,NaN,SANTANDER,LOS_SANTOS,5.0,8.3,11.9,Revisado
74732,2009-06-11,10:44:02,6.844,-73.157,143.6,2.7,NaN,SANTANDER,LOS_SANTOS,4.5,8.7,12.9,Revisado
74733,2009-06-11,10:44:02,6.844,-73.157,143.6,2.7,NaN,SANTANDER,LOS_SANTOS,4.5,8.7,12.9,Revisado
74734,2009-06-11,10:44:02,6.814,-73.127,139.8,2.8,NaN,SANTANDER,LOS_SANTOS,5.0,8.3,11.9,Revisado
74735,2009-06-11,10:53:31,6.794,-73.106,146.8,2.4,NaN,SANTANDER,LOS_SANTOS,7.4,14.6,20.7,Revisado
74736,2009-06-11,10:53:31,6.794,-73.106,146.8,2.4,NaN,SANTANDER,LOS_SANTOS,7.4,14.6,20.7,Revisado
74737,2009-06-11,10:53:31,6.827,-73.158,148.0,2.7,NaN,SANTANDER,LOS_SANTOS,5.2,9.8,15.3,Revisado
74738,2009-06-11,10:53:31,6.827,-73.158,148.0,2.7,NaN,SANTANDER,LOS_SANTOS,5.2,9.8,15.3,Revisado
74739,2009-06-11,16:45:57,4.248,-75.972,4.5,2.4,NaN,VALLE DEL CAUCA,SEVILLA,8.0,11.0,14.7,Revisado
74740,2009-06-11,16:45:57,4.248,-75.972,4.5,2.4,NaN,VALLE DEL CAUCA,SEVILLA,8.0,11.0,14.7,Revisado
74741,2009-06-11,19:00:18,4.464,-73.659,1.5,2.9,NaN,META,SAN_JUANITO,7.0,9.7,11.9,Revisado
74742,2009-06-11,19:00:18,4.464,-73.659,1.5,2.9,NaN,META,SAN_JUANITO,7.0,9.7,11.9,Revisado
74743,2009-06-11,22:47:18,6.495,-75.894,76.0,1.8,NaN,ANTIOQUIA,SANTA_FE_ANTIOQUIA,3.0,7.8,7.5,Revisado
74744,2009-06-11,22:47:18,6.495,-75.894,76.0,1.8,NaN,ANTIOQUIA,SANTA_FE_ANTIOQUIA,3.0,7.8,7.5,Revisado
74745,2009-06-11,23:56:58,5.064,-76.781,32.0,2.9,NaN,CHOCO,MEDIO_SAN_JUAN,12.0,10.3,43.1,Revisado
74746,2009-06-11,23:56:58,5.064,-76.781,32.0,2.9,NaN,CHOCO,MEDIO_SAN_JUAN,12.0,10.3,43.1,Revisado
148985,2012-02-08,10:33:32,4.228,-76.814,17.8,1.6,NaN,VALLE DEL CAUCA,BUENAVENTURA,1.9,3.5,5.8,Revisado
148986,2012-02-08,10:33:32,4.228,-76.814,17.8,1.6,NaN,VALLE DEL CAUCA,BUENAVENTURA,1.9,3.5,5.8,Revisado
150180,2012-03-07,09:18:55,4.028,-75.925,167.8,2.6,NaN,QUINDIO,GENOVA,3.9,5.4,6.2,Revisado
150181,2012-03-07,09:18:55,4.028,-75.925,167.8,2.6,NaN,QUINDIO,GENOVA,3.9,5.4,6.2,Revisado
150781,2012-03-25,08:11:51,6.774,-73.133,144.8,2.5,NaN,SANTANDER,LOS_SANTOS,2.6,3.6,4.6,Revisado
150782,2012-03-25,08:11:51,6.774,-73.133,144.8,2.5,NaN,SANTANDER,LOS_SANTOS,2.6,3.6,4.6,Revisado
168884,2013-08-26,00:06:44,7.708,-75.024,18.2,1.8,NaN,ANTIOQUIA,EL_BAGRE,3.4,3.7,4.5,Revisado
168885,2013-08-26,00:06:44,7.708,-75.024,18.2,1.8,NaN,ANTIOQUIA,EL_BAGRE,3.4,3.7,4.5,Revisado

In [14]:
seismic_1st_batch = seismic_1st_batch.drop_duplicates()
seismic_1st_batch[seismic_1st_batch.duplicated(subset=seismic_1st_batch.columns, keep=False)]

Empty DataFrame
Columns: [FECHA, HORA_UTC, LAT, LONG, PROF., MAGNITUD Ml, MAGNITUD Mw, DEPARTAMENTO, MUNICIPIO, ERR-LAT, ERR-LONG, ERR-PROF, ESTADO]
Index: []

In [15]:
seismic_2nd_batch[seismic_2nd_batch.duplicated(subset=seismic_2nd_batch.columns, keep=False)]

Empty DataFrame
Columns: [FECHA - HORA UTC, LAT, LONG, PROF., MAGNITUD, TIPO MAGNITUD, ERR-LAT, ERR-LONG, ERR-PROF, REGION, ESTADO]
Index: []

### Checking for NaN

In [16]:
print("NaN:\n")
print(seismic_1st_batch.isna().sum())
print("\n Missing cells\n", seismic_1st_batch.isna().sum().sum())

NaN:

FECHA                0
HORA_UTC             0
LAT                  0
LONG                 0
PROF.                0
MAGNITUD Ml          0
MAGNITUD Mw     168704
DEPARTAMENTO         0
MUNICIPIO            0
ERR-LAT            189
ERR-LONG           189
ERR-PROF           189
ESTADO               0
dtype: int64

 Missing cells
 169271

In [17]:
print("NaN:\n")
print(seismic_2nd_batch.isna().sum())
print("\n Missing cells\n", seismic_2nd_batch.isna().sum().sum())

NaN:

FECHA - HORA UTC    0
LAT                 0
LONG                0
PROF.               0
MAGNITUD            0
TIPO MAGNITUD       0
ERR-LAT             0
ERR-LONG            0
ERR-PROF            0
REGION              0
ESTADO              0
dtype: int64

 Missing cells
 0

### Zoom in on missing values

In [49]:
tmp = np.where(seismic_1st_batch['MAGNITUD Mw'].notnull())
print("Number of NaN:", tmp[0].size)

for i in range(5): #len(tmp[0])):
    index = tmp[0][i]
    #print(seismic_1st_batch[['MAGNITUD Ml', 'MAGNITUD Mw']].iloc[index])
    if seismic_1st_batch['MAGNITUD Ml'].iloc[index] == np.nan:
        print("Index with empty value for MAGNITUD Ml")

Number of NaN: 4544

As we can see, there are just four values for Mw with the respectiv Ml, so may no sense to keep the Mw magnitued column

In [50]:
seismic_1st_batch.drop(columns='MAGNITUD Mw', inplace=True)
seismic_1st_batch.rename(columns={'MAGNITUD Ml': 'MAGNITUD'}, inplace=True)
print("NaN:\n")
print(seismic_1st_batch.isna().sum())

NaN:

FECHA             0
HORA_UTC          0
LAT               0
LONG              0
PROF.             0
MAGNITUD          0
DEPARTAMENTO      0
MUNICIPIO         0
ERR-LAT         189
ERR-LONG        189
ERR-PROF        189
ESTADO            0
dtype: int64

Regardin the missing values for Latitude, longitude, and deep errors, lets replace them with the respective average

In [51]:
aveErrLat = seismic_1st_batch['ERR-LAT'].mean()
aveErrLon = seismic_1st_batch['ERR-LONG'].mean()
aveErrPro = seismic_1st_batch['ERR-PROF'].mean()
#
seismic_1st_batch['ERR-LAT'].fillna(aveErrLat, inplace=True)
seismic_1st_batch['ERR-LONG'].fillna(aveErrLon, inplace=True)
seismic_1st_batch['ERR-PROF'].fillna(aveErrPro, inplace=True)
#
print("NaN:\n")
print(seismic_1st_batch.isna().sum())

NaN:

FECHA           0
HORA_UTC        0
LAT             0
LONG            0
PROF.           0
MAGNITUD        0
DEPARTAMENTO    0
MUNICIPIO       0
ERR-LAT         0
ERR-LONG        0
ERR-PROF        0
ESTADO          0
dtype: int64

In [53]:
# Merging columns FECHA and HORA_UTC
seismic_1st_batch['FECHA - HORA UTC'] = seismic_1st_batch['FECHA'] + ' ' + seismic_1st_batch['HORA_UTC']
seismic_1st_batch.drop(columns=['FECHA', 'HORA_UTC'], inplace=True)

for i in seismic_1st_batch.columns.to_list():
    print(i)

LAT
LONG
PROF.
MAGNITUD
DEPARTAMENTO
MUNICIPIO
ERR-LAT
ERR-LONG
ERR-PROF
ESTADO
FECHA - HORA UTC

### Checking for magnitudes in the second batch

In [54]:
for i in seismic_2nd_batch['TIPO MAGNITUD'].value_counts().index:
    print(i)

MLr_3
MLr_2
MLr_1
MLr_vmm
MLr_4
MLr
M_MLr
MLr_5
M
Mw(mB)
Mw
mb
Mwp
MLv
Mw(Mwp)
ML
mB

As an approach, for this analysis we are considering all the magnitudes as Ml, __even though they are not__.  
So, lets drop the column 'TIPO DE MAGNITUD'

In [55]:
seismic_2nd_batch.drop(columns='TIPO MAGNITUD', inplace=True)
seismic_2nd_batch.columns.to_list()

['FECHA - HORA UTC',
 'LAT',
 'LONG',
 'PROF.',
 'MAGNITUD',
 'ERR-LAT',
 'ERR-LONG',
 'ERR-PROF',
 'REGION',
 'ESTADO']

Lest zoom in on MUNICIPO and DEPARTAMENTE, first batch, and for REGION, second batch

In [56]:
print(seismic_1st_batch[['MUNICIPIO', 'DEPARTAMENTO']].iloc[1])
print("\n")
print(seismic_2nd_batch['REGION'].iloc[1])

MUNICIPIO       LOS_SANTOS
DEPARTAMENTO     SANTANDER
Name: 1, dtype: object


Tame - Arauca, Colombia

In this case, "REGION: Los Santons - Santander, Colombia" means:  
- MUNICIPIO = Tame
- DEPARTAMENTO = Arauca

So, lets put into the column REGION just the MUNICIPIO, create a new column DEPARTAMENTO by putting the respective value, and rename REGION as MUNICIPIO

In [57]:
tmp_a = seismic_2nd_batch['REGION'].str.split('-').str[0].str.strip()
tmp_b = seismic_2nd_batch['REGION'].str.split(',').str[0].str.strip()
tmp_c = tmp_b.str.split('-').str[1].str.strip()
#
seismic_2nd_batch['REGION'] = tmp_a
seismic_2nd_batch['DEPARTAMENTO'] = tmp_c

seismic_2nd_batch.rename(columns={'REGION': 'MUNICIPIO'}, inplace=True)
seismic_2nd_batch[['MUNICIPIO', 'DEPARTAMENTO']].iloc[1]

MUNICIPIO         Tame
DEPARTAMENTO    Arauca
Name: 1, dtype: object

### Checking if missing values

In [58]:
seismic_2nd_batch.isna().sum()

FECHA - HORA UTC       0
LAT                    0
LONG                   0
PROF.                  0
MAGNITUD               0
ERR-LAT                0
ERR-LONG               0
ERR-PROF               0
MUNICIPIO              0
ESTADO                 0
DEPARTAMENTO        6520
dtype: int64

In [92]:
tmp_df = seismic_2nd_batch[seismic_2nd_batch['DEPARTAMENTO'].isna()]
tmp_df['MUNICIPIO'].value_counts()

Océano Pacífico                               2925
Mar Caribe                                    1302
Venezuela                                      799
Area de Influencia Volcán Nevado del Huila     449
Norte Colombia                                 174
Caribbean Sea                                  173
Panama                                         143
Cerca de la Costa de Colombia                  137
Área de Influencia Volcán Nevado del Huila      91
Cerca de la Costa de Venezuela                  66
Sur de Panama                                   55
Northern Colombia                               29
Volcán Chiles                                   28
Cerca de la Costa de Ecuador                    26
Cerca de la Costa Oeste de Colombia             25
Near North Coast of Colombia                    21
Near Coast of Venezuela                         15
Colombia                                         9
Área de Influencia Volcán Chiles                 7
Volcán Galeras                                   6
Near West Coast of Colombia                      5
Costa Rica                                       4
Norte de Panama                                  4
Ecuador                                          2
North of Panama                                  2
Lago Maracaibo, Venezuela                        2
Central America                                  1
South of Panama                                  1
Volcan Galeras                                   1
Volcán Nevado del Ruiz                           1
Volcán Cerro Negro                               1
Masachapa, Nicaragua                             1
Quesada, Guatemala                               1
Lake Maracaibo, Venezuela                        1
Costa Afuera de Centro America                   1
Off Coast of Central America                     1
Nicaragua                                        1
Puerto El Triunfo, El Salvador                   1
Norte de Peru                                    1
La Cruz, Costa Rica                              1
Área de Influencia Volcán Cerro Negro            1
Área de Influencia Volcán Azufral                1
Brasil Occidental                                1
Limones, Panama                                  1
off the coast of Central America                 1
off the coast of Central America.                1
Volcán Las Animas                                1
Name: MUNICIPIO, dtype: int64

As we can see, all this seismics were located outside, or close by, the Colombia's border, so lets to drop them

In [93]:
tmp_index = seismic_2nd_batch[seismic_2nd_batch.isna().any(axis=1)].index
seismic_2nd_batch = seismic_2nd_batch.drop(tmp_index)

seismic_2nd_batch.isna().sum()

FECHA - HORA UTC    0
LAT                 0
LONG                0
PROF.               0
MAGNITUD            0
ERR-LAT             0
ERR-LONG            0
ERR-PROF            0
MUNICIPIO           0
ESTADO              0
DEPARTAMENTO        0
dtype: int64

In [94]:
for i in seismic_1st_batch.columns.to_list():
    print(i)
print(seismic_1st_batch.shape)
print("\n")
for i in seismic_2nd_batch.columns.to_list():
    print(i)
print(seismic_2nd_batch.shape)

LAT
LONG
PROF.
MAGNITUD
DEPARTAMENTO
MUNICIPIO
ERR-LAT
ERR-LONG
ERR-PROF
ESTADO
FECHA - HORA UTC
(173248, 11)


FECHA - HORA UTC
LAT
LONG
PROF.
MAGNITUD
ERR-LAT
ERR-LONG
ERR-PROF
MUNICIPIO
ESTADO
DEPARTAMENTO
(119939, 11)

In [100]:
seismic_merged = pd.concat([seismic_1st_batch, seismic_2nd_batch])
seismic_merged = seismic_merged.reset_index(drop=True)

In [101]:
for i in seismic_merged.columns.to_list():
    print(i)
print(seismic_merged.shape)

LAT
LONG
PROF.
MAGNITUD
DEPARTAMENTO
MUNICIPIO
ERR-LAT
ERR-LONG
ERR-PROF
ESTADO
FECHA - HORA UTC
(293187, 11)

In [102]:
print("NaN:\n")
print(seismic_merged.isna().sum(), '\n')

NaN:

LAT                 0
LONG                0
PROF.               0
MAGNITUD            0
DEPARTAMENTO        0
MUNICIPIO           0
ERR-LAT             0
ERR-LONG            0
ERR-PROF            0
ESTADO              0
FECHA - HORA UTC    0
dtype: int64

In [103]:
profile = ProfileReport(seismic_merged, title="Seismic from 1st Jan. 1993 to 31st May 2023")
profile.to_file("report_1st_jan_93_to_31st_may_23.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## Saving the Dataframe into a CSV and XLSX file

In [105]:
seismic_merged.to_csv('data/seismic_1st_jan_93_to_31st_may_23.csv', index=False)
seismic_merged.to_excel('data/seismic_1st_jan_93_to_31st_may_23.xlsx', index=False)